-- Feel free to modify this file to match your development goal.
-- Here we only create 3 tables for demo purpose.

CREATE TABLE Users (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    balance INTEGER DEFAULT 0 CHECK (balance>=0),
    address VARCHAR(255) NOT NULL
);

CREATE TABLE Sellers (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY REFERENCES Users(id)
);

CREATE TABLE Products (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    description VARCHAR(255),
    available BOOLEAN DEFAULT TRUE,
    category VARCHAR(255) NOT NULL,
    image_file VARCHAR(255) NOT NULL
);

CREATE TABLE Orders (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    bid INT NOT NULL REFERENCES Users(id),
    address VARCHAR(255),
    placed_datetime TIMESTAMP NOT NULL,
    completed_status BOOLEAN DEFAULT FALSE,
    completion_datetime TIMESTAMP DEFAULT NULL
);

CREATE TABLE Purchases (
    oid INT NOT NULL REFERENCES Orders(id),
    pid INT NOT NULL REFERENCES Products(id),
    price DECIMAL(12,2) NOT NULL,
    quantity INT NOT NULL DEFAULT 0,
    completed_status BOOLEAN DEFAULT FALSE,
    completion_datetime TIMESTAMP DEFAULT NULL,
    PRIMARY KEY(oid, pid)
);

CREATE TABLE Inventory (
    pid INT NOT NULL REFERENCES Products(id),
    sid INT NOT NULL REFERENCES Sellers(id),
    price DECIMAL(12,2) NOT NULL,
    quantity INT NOT NULL DEFAULT 0,
    PRIMARY KEY(pid, sid)
);

CREATE TABLE Cart (
    id INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    sid INT NOT NULL REFERENCES Sellers(id),
    quantity INT NOT NULL DEFAULT 1,
    price DECIMAL(12,2) NOT NULL,
    wishlist BOOLEAN DEFAULT FALSE
    PRIMARY KEY(id, pid, sid)
)
